# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

grouplassoLossCpp <- function(groups, grouplasso, W, Q) {
    .Call(`_testPackage_grouplassoLossCpp`, groups, grouplasso, W, Q)
}

grouplassoPenaltyCpp <- function(groups, W, DG, Q) {
    invisible(.Call(`_testPackage_grouplassoPenaltyCpp`, groups, W, DG, Q))
}

elitistLossCpp <- function(groups, elitistlasso, W, Q) {
    .Call(`_testPackage_elitistLossCpp`, groups, elitistlasso, W, Q)
}

elitistPenaltyCpp <- function(groups, W, DE, Q) {
    invisible(.Call(`_testPackage_elitistPenaltyCpp`, groups, W, DE, Q))
}

lossFunctionCpp <- function(X, W, P, groups, ridge, lasso, grouplasso, elitistlasso, Q) {
    .Call(`_testPackage_lossFunctionCpp`, X, W, P, groups, ridge, lasso, grouplasso, elitistlasso, Q)
}

coordinateDescentStepCpp <- function(XtXP, XtX, W, constraints, Q, J, D) {
    invisible(.Call(`_testPackage_coordinateDescentStepCpp`, XtXP, XtX, W, constraints, Q, J, D))
}

coordinateDescentCpp <- function(X, XtX, XtXP, itrCoor, W, constraints, P, D, Q, J, printLoss) {
    invisible(.Call(`_testPackage_coordinateDescentCpp`, X, XtX, XtXP, itrCoor, W, constraints, P, D, Q, J, printLoss))
}

makeConstraints <- function(constraints, Q) {
    .Call(`_testPackage_makeConstraints`, constraints, Q)
}

newAlgoCpp <- function(X, ridge, lasso, constraints, grouplasso, elitistlasso, groups, Q, itr, Wstart, nStarts = 1L, printLoss = TRUE, coorDec = FALSE) {
    .Call(`_testPackage_newAlgoCpp`, X, ridge, lasso, constraints, grouplasso, elitistlasso, groups, Q, itr, Wstart, nStarts, printLoss, coorDec)
}

rcpparma_hello_world <- function() {
    .Call(`_testPackage_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_testPackage_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_testPackage_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_testPackage_rcpparma_bothproducts`, x)
}

